#include <cctype>
#include <sstream>
#include "Generator.h"

using namespace lyra::reflect;

static std::string to_upper_snake(std::string_view name)
{
    std::string result;
    for (char c : name) {
        if (std::isalnum(static_cast<unsigned char>(c))) {
            result += static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
        } else {
            result += '_';
        }
    }
    return result;
}

std::string Generator::generate(const ModuleReflection& module)
{
    std::ostringstream ss;
    std::string        guard = "LYRA_GENERATED_" + to_upper_snake(module.module_name) + "_GEN_H";

    ss << "// Generated by lyra-reflect. DO NOT EDIT DIRECTLY.\n";
    ss << "#pragma once\n\n";
    ss << "#ifndef " << guard << "\n";
    ss << "#define " << guard << "\n\n";

    ss << "#include <tuple>\n";
    ss << "#include <cstddef>\n";
    ss << "#include <iterator>\n";
    ss << "#include <Lyra/Utilities/Stdint.h>\n";
    ss << "#include <Lyra/Utilities/String.h>\n";
    ss << "#include <Lyra/Scene/World.h>\n";
    ss << "#include <Lyra/Scripting/ScriptTypes.h>\n";
    ss << "#include <Lyra/Scripting/ScriptContext.h>\n";
    ss << "#include <Lyra/Scripting/Disabled.h>\n\n";

    // Include original source headers
    ss << "// Annotated source headers\n";
    for (const auto& header : module.included_headers) {
        ss << "#include \"" << header << "\"\n";
    }
    ss << "\n";

    ss << "namespace lyra::generated\n{\n";

    // 1. Thunks for each system
    ss << "    // =========================================================================\n";
    ss << "    // System Execution Thunks\n";
    ss << "    // =========================================================================\n\n";

    for (const auto& sys : module.systems) {
        ss << "    inline void " << sys.name << "__run(ScriptContext& ctx)\n    {\n";

        // Check parameter profile: ctx only, per-entity components, or queries
        std::vector<ParamMeta> comp_params;
        std::vector<ParamMeta> query_params;

        for (size_t i = 0; i < sys.params.size(); ++i) {
            if (i == 0 && (sys.params[i].type == "ScriptContext" || sys.params[i].type == "lyra::ScriptContext")) {
                continue;
            }
            if (sys.params[i].is_query) {
                query_params.push_back(sys.params[i]);
            } else {
                comp_params.push_back(sys.params[i]);
            }
        }

        if (!query_params.empty()) {
            // General query call
            ss << "        " << sys.name << "(ctx";
            for (const auto& q : query_params) {
                ss << ", ctx.query<";
                for (size_t qi = 0; qi < q.query_subtypes.size(); ++qi) {
                    if (qi > 0) ss << ", ";
                    if (q.query_subtypes[qi].is_const) ss << "const ";
                    ss << q.query_subtypes[qi].type;
                }
                ss << ">()";
            }
            ss << ");\n";
        } else if (!comp_params.empty()) {
            // Batched each loop
            ss << "        ctx.each<";
            for (size_t ci = 0; ci < comp_params.size(); ++ci) {
                if (ci > 0) ss << ", ";
                if (comp_params[ci].is_const) ss << "const ";
                ss << comp_params[ci].type;
            }
            ss << ">([&](";
            for (size_t ci = 0; ci < comp_params.size(); ++ci) {
                if (ci > 0) ss << ", ";
                if (comp_params[ci].is_const) ss << "const ";
                ss << comp_params[ci].type << "& a" << ci;
            }
            ss << ") {\n";
            ss << "            " << sys.name << "(ctx";
            for (size_t ci = 0; ci < comp_params.size(); ++ci) {
                ss << ", a" << ci;
            }
            ss << ");\n";
            ss << "        });\n";
        } else {
            // No parameters other than context
            ss << "        " << sys.name << "(ctx);\n";
        }

        ss << "    }\n\n";

        // Query descriptors for this system
        if (!comp_params.empty()) {
            ss << "    inline constexpr ComponentID " << sys.name << "__q0_req[] = { ";
            for (size_t ci = 0; ci < comp_params.size(); ++ci) {
                if (ci > 0) ss << ", ";
                ss << "hash_script_name(\"" << comp_params[ci].type << "\")";
            }
            ss << " };\n";

            ss << "    inline constexpr bool " << sys.name << "__q0_w[] = { ";
            for (size_t ci = 0; ci < comp_params.size(); ++ci) {
                if (ci > 0) ss << ", ";
                ss << (comp_params[ci].is_const ? "false" : "true");
            }
            ss << " };\n";

            ss << "    inline constexpr QueryDesc " << sys.name << "__queries[] = {\n";
            ss << "        { " << sys.name << "__q0_req, " << sys.name << "__q0_w, "
               << comp_params.size() << ", nullptr, 0 }\n";
            ss << "    };\n\n";
        } else {
            ss << "    inline constexpr QueryDesc " << sys.name << "__queries[] = {};\n\n";
        }
    }

    // 2. Script descriptors table
    ss << "    // =========================================================================\n";
    ss << "    // Script Descriptors Table\n";
    ss << "    // =========================================================================\n\n";

    ss << "    inline constexpr ScriptDesc script_descriptors[] = {\n";
    for (size_t i = 0; i < module.systems.size(); ++i) {
        const auto& sys = module.systems[i];
        ss << "        {\n";
        ss << "            .name        = \"" << sys.name << "\",\n";
        if (!sys.group.empty()) {
            ss << "            .group       = \"" << sys.group << "\",\n";
        } else {
            ss << "            .group       = nullptr,\n";
        }
        ss << "            .stage       = AppEvent::" << sys.stage << ",\n";
        if (sys.run_in_editor) {
            ss << "            .flags       = ScriptFlag::RUN_IN_EDITOR,\n";
        } else {
            ss << "            .flags       = ScriptFlag::NONE,\n";
        }
        ss << "            .state_size  = 0,\n";
        ss << "            .state_align = 0,\n";
        ss << "            .queries     = " << sys.name << "__queries,\n";
        ss << "            .query_count = " << (sys.params.size() > 1 ? "1" : "0") << ",\n";
        ss << "        }";
        if (i + 1 < module.systems.size()) ss << ",";
        ss << "\n";
    }
    ss << "    };\n\n";

    // 3. Component pool pre-registration helper
    ss << "    // =========================================================================\n";
    ss << "    // Component Pool Pre-registration\n";
    ss << "    // =========================================================================\n\n";

    ss << "    inline void preregister_component_pools(World& world)\n    {\n";
    for (const auto& comp : module.components) {
        ss << "        std::ignore = world.registry.storage<" << comp.name << ">();\n";
        ss << "        std::ignore = world.registry.storage<Disabled<" << comp.name << ">>();\n";
    }
    ss << "    }\n\n";

    // 4. ScriptAPI factory
    ss << "    // =========================================================================\n";
    ss << "    // ScriptAPI Factory\n";
    ss << "    // =========================================================================\n\n";

    ss << "    inline auto create_script_api() -> ScriptAPI\n    {\n";
    ss << "        return ScriptAPI{\n";
    ss << "            .get_api_name = []() -> CString { return \"" << module.module_name << "\"; },\n";
    ss << "            .get_scripts = [](ScriptDesc* out) -> uint {\n";
    ss << "                constexpr uint count = static_cast<uint>(std::size(script_descriptors));\n";
    ss << "                if (!out) {\n";
    ss << "                    return count;\n";
    ss << "                }\n";
    ss << "                for (uint i = 0; i < count; ++i) {\n";
    ss << "                    out[i] = script_descriptors[i];\n";
    ss << "                }\n";
    ss << "                return count;\n";
    ss << "            },\n";
    ss << "            .run = [](ScriptID id, ScriptContext& ctx) {\n";

    for (const auto& sys : module.systems) {
        ss << "                if (id == hash_script_name(\"" << sys.name << "\")) {\n";
        ss << "                    " << sys.name << "__run(ctx);\n";
        ss << "                    return;\n";
        ss << "                }\n";
    }

    ss << "            },\n";
    ss << "            .get_params = nullptr,\n";
    ss << "        };\n";
    ss << "    }\n\n";

    ss << "} // namespace lyra::generated\n\n";
    ss << "#endif // " << guard << "\n";

    return ss.str();
}
