// Generated by lyra-reflect. DO NOT EDIT DIRECTLY.
#pragma once

#ifndef LYRA_GENERATED_SAMPLESCRIPTS_GEN_H
#define LYRA_GENERATED_SAMPLESCRIPTS_GEN_H

#include <tuple>
#include <cstddef>
#include <iterator>
#include <Lyra/Utilities/Stdint.h>
#include <Lyra/Utilities/String.h>
#include <Lyra/Scene/World.h>
#include <Lyra/Scripting/ScriptTypes.h>
#include <Lyra/Scripting/ScriptContext.h>
#include <Lyra/Scripting/Disabled.h>

// Annotated source headers
#include "SampleScripts.h"

namespace lyra::generated
{
    // =========================================================================
    // System Execution Thunks
    // =========================================================================

    inline void orbit__run(ScriptContext& ctx)
    {
        ctx.each<OrbitCamera, lyra::TransformLocal>([&](OrbitCamera& a0, lyra::TransformLocal& a1) {
            orbit(ctx, a0, a1);
        });
    }

    inline constexpr ComponentID orbit__q0_req[] = { hash_script_name("OrbitCamera"), hash_script_name("lyra::TransformLocal") };
    inline constexpr bool orbit__q0_w[] = { true, true };
    inline constexpr QueryDescriptor orbit__queries[] = {
        { orbit__q0_req, orbit__q0_w, 2, nullptr, 0 }
    };

    // =========================================================================
    // Script Descriptors Table
    // =========================================================================

    inline constexpr ScriptDescriptor script_descriptors[] = {
        {
            .name        = "orbit",
            .group       = "Gameplay/Camera",
            .stage       = AppEvent::UPDATE,
            .flags       = ScriptFlag::NONE,
            .state_size  = 0,
            .state_align = 0,
            .queries     = orbit__queries,
            .query_count = 1,
        }
    };

    // =========================================================================
    // Component Pool Pre-registration
    // =========================================================================

    inline void preregister_component_pools(World& world)
    {
        std::ignore = world.registry.storage<OrbitCamera>();
        std::ignore = world.registry.storage<Disabled<OrbitCamera>>();
    }

    // =========================================================================
    // ScriptAPI Factory
    // =========================================================================

    inline auto create_script_api() -> ScriptAPI
    {
        return ScriptAPI{
            .get_api_name = []() -> CString { return "SampleScripts"; },
            .get_scripts = [](ScriptDescriptor* out) -> uint {
                constexpr uint count = static_cast<uint>(std::size(script_descriptors));
                if (!out) {
                    return count;
                }
                for (uint i = 0; i < count; ++i) {
                    out[i] = script_descriptors[i];
                }
                return count;
            },
            .run = [](ScriptID id, ScriptContext& ctx) {
                if (id == hash_script_name("orbit")) {
                    orbit__run(ctx);
                    return;
                }
            },
            .get_params = nullptr,
        };
    }

} // namespace lyra::generated

#endif // LYRA_GENERATED_SAMPLESCRIPTS_GEN_H
