#include <cctype>
#include <sstream>
#include <iostream>
#include "Generator.h"

using namespace lyra::reflect;

static std::string to_upper_snake(std::string_view name)
{
    std::string result;
    for (size_t i = 0; i < name.size(); ++i) {
        char c = name[i];
        if (i > 0 && std::isupper(static_cast<unsigned char>(c)) &&
            (std::islower(static_cast<unsigned char>(name[i - 1])) ||
                (i + 1 < name.size() && std::islower(static_cast<unsigned char>(name[i + 1]))))) {
            result += '_';
        }
        if (std::isalnum(static_cast<unsigned char>(c))) {
            result += static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
        } else {
            result += '_';
        }
    }
    return result;
}

static std::string to_lower_snake(std::string_view name)
{
    std::string result;
    for (size_t i = 0; i < name.size(); ++i) {
        char c = name[i];
        if (i > 0 && std::isupper(static_cast<unsigned char>(c)) &&
            (std::islower(static_cast<unsigned char>(name[i - 1])) ||
                (i + 1 < name.size() && std::islower(static_cast<unsigned char>(name[i + 1]))))) {
            result += '_';
        }
        if (std::isalnum(static_cast<unsigned char>(c))) {
            result += static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
        } else {
            result += '_';
        }
    }
    return result;
}

static bool ends_with(std::string_view str, std::string_view suffix)
{
    return str.size() >= suffix.size() &&
           str.compare(str.size() - suffix.size(), suffix.size(), suffix) == 0;
}

static std::string to_display_label(std::string_view name)
{
    std::string result;

    bool capitalize_next = true;
    for (char c : name) {
        if (c == '_') {
            result += ' ';
            capitalize_next = true;
        } else if (capitalize_next) {
            result += static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
            capitalize_next = false;
        } else {
            result += c;
        }
    }
    return result;
}

static std::string to_display_title(std::string_view name)
{
    std::string result;
    for (size_t i = 0; i < name.size(); ++i) {
        char c = name[i];
        if (i > 0 && std::isupper(static_cast<unsigned char>(c)) &&
            std::islower(static_cast<unsigned char>(name[i - 1]))) {
            result += ' ';
        }
        result += c;
    }
    return result;
}

std::string Generator::generate(const ModuleReflection& module, const std::string& output_filename)
{
    std::ostringstream ss;

    bool is_cpp = ends_with(output_filename, ".cpp") || ends_with(output_filename, ".cxx") || ends_with(output_filename, ".cc");

    std::string guard = "LYRA_GENERATED_" + to_upper_snake(module.module_name) + "_GEN_H";
    ss << "// Generated by lyra-bindgen. DO NOT EDIT DIRECTLY.\n";
    if (!is_cpp) {
        ss << "#pragma once\n\n";
        ss << "#ifndef " << guard << "\n";
        ss << "#define " << guard << "\n\n";
    } else {
        ss << "\n";
    }

    ss << "#include <tuple>\n";
    ss << "#include <cstddef>\n";
    ss << "#include <iterator>\n";
    ss << "#include <Lyra/Lyra.hpp>\n";
    ss << "#include <Lyra/Scripting/ScriptTypes.h>\n";
    ss << "#include <Lyra/Scripting/ScriptContext.h>\n";
    ss << "#include <Lyra/Scripting/Disabled.h>\n\n";

    // Include original source headers
    ss << "// Annotated source headers\n";
    for (const auto& header : module.included_headers) {
        if (!module.include_prefix.empty()) {
            ss << "#include <" << module.include_prefix << "/" << header << ">\n";
        } else {
            ss << "#include \"" << header << "\"\n";
        }
    }
    ss << "\n";
    ss << "using namespace lyra;\n\n";

    if (!module.systems.empty()) {
        ss << "// Forward declarations of module systems\n";
        for (const auto& sys : module.systems) {
            if (!sys.namespace_scope.empty()) {
                ss << "namespace " << sys.namespace_scope << "\n{\n";
                ss << "    void " << sys.name << "(";
                for (size_t pi = 0; pi < sys.params.size(); ++pi) {
                    if (pi > 0) ss << ", ";
                    ss << sys.params[pi].raw_type;
                }
                ss << ");\n";
                ss << "} // namespace " << sys.namespace_scope << "\n";
            } else {
                ss << "void " << sys.name << "(";
                for (size_t pi = 0; pi < sys.params.size(); ++pi) {
                    if (pi > 0) ss << ", ";
                    ss << sys.params[pi].raw_type;
                }
                ss << ");\n";
            }
        }
        ss << "\n";
    }

    // each module gets its own namespace so inline symbols never collide across translation units
    ss << "namespace lyra::generated::" << to_lower_snake(module.module_name) << "\n{\n";

    // 1. Thunks for each system
    ss << "    // =========================================================================\n";
    ss << "    // System Execution Thunks\n";
    ss << "    // =========================================================================\n\n";

    for (const auto& sys : module.systems) {
        std::string call_name = sys.namespace_scope.empty() ? ("::" + sys.name) : (sys.namespace_scope + "::" + sys.name);
        ss << "    inline void " << sys.name << "__run(ScriptContext& ctx)\n    {\n";

        // Check parameter profile: ctx only, per-entity components, or queries
        std::vector<ParamMeta> comp_params;
        std::vector<ParamMeta> query_params;

        for (size_t i = 0; i < sys.params.size(); ++i) {
            if (i == 0 && (sys.params[i].type == "ScriptContext" || sys.params[i].type == "lyra::ScriptContext")) {
                continue;
            }
            if (sys.params[i].is_query) {
                query_params.push_back(sys.params[i]);
            } else {
                comp_params.push_back(sys.params[i]);
            }
        }

        if (!query_params.empty()) {
            // General query call
            ss << "        " << call_name << "(ctx";
            for (const auto& q : query_params) {
                ss << ", ctx.query<";
                for (size_t qi = 0; qi < q.query_subtypes.size(); ++qi) {
                    if (qi > 0) ss << ", ";
                    if (q.query_subtypes[qi].is_const) ss << "const ";
                    ss << q.query_subtypes[qi].type;
                }
                ss << ">()";
            }
            ss << ");\n";
        } else if (!comp_params.empty()) {
            // Batched each loop
            ss << "        ctx.each<";
            for (size_t ci = 0; ci < comp_params.size(); ++ci) {
                if (ci > 0) ss << ", ";
                if (comp_params[ci].is_const) ss << "const ";
                ss << comp_params[ci].type;
            }
            ss << ">([&](";
            for (size_t ci = 0; ci < comp_params.size(); ++ci) {
                if (ci > 0) ss << ", ";
                if (comp_params[ci].is_const) ss << "const ";
                ss << comp_params[ci].type << "& a" << ci;
            }
            ss << ") {\n";
            ss << "            " << call_name << "(ctx";
            for (size_t ci = 0; ci < comp_params.size(); ++ci) {
                ss << ", a" << ci;
            }
            ss << ");\n";
            ss << "        });\n";
        } else {
            // No parameters other than context
            ss << "        " << call_name << "(ctx);\n";
        }

        ss << "    }\n\n";

        // Query descriptors for this system
        if (!comp_params.empty()) {
            ss << "    inline constexpr ComponentID " << sys.name << "__q0_req[] = { ";
            for (size_t ci = 0; ci < comp_params.size(); ++ci) {
                if (ci > 0) ss << ", ";
                ss << "hash_script_name(\"" << comp_params[ci].type << "\")";
            }
            ss << " };\n";

            ss << "    inline constexpr bool " << sys.name << "__q0_w[] = { ";
            for (size_t ci = 0; ci < comp_params.size(); ++ci) {
                if (ci > 0) ss << ", ";
                ss << (comp_params[ci].is_const ? "false" : "true");
            }
            ss << " };\n";

            ss << "    inline constexpr QueryDescriptor " << sys.name << "__queries[] = {\n";
            ss << "        { " << sys.name << "__q0_req, " << sys.name << "__q0_w, "
               << comp_params.size() << ", nullptr, 0 }\n";
            ss << "    };\n\n";
        } else {
            ss << "    inline constexpr const QueryDescriptor* " << sys.name << "__queries = nullptr;\n\n";
        }
    }

    // 2. Script descriptors table
    ss << "    // =========================================================================\n";
    ss << "    // Script Descriptors Table\n";
    ss << "    // =========================================================================\n\n";

    if (module.systems.empty()) {
        ss << "    inline constexpr const ScriptDescriptor* script_descriptors = nullptr;\n\n";
    } else {
        ss << "    inline constexpr ScriptDescriptor script_descriptors[] = {\n";
        for (size_t i = 0; i < module.systems.size(); ++i) {
            const auto& sys = module.systems[i];
            ss << "        {\n";
            ss << "            .name        = \"" << sys.name << "\",\n";
            if (!sys.group.empty()) {
                ss << "            .group       = \"" << sys.group << "\",\n";
            } else {
                ss << "            .group       = nullptr,\n";
            }
            ss << "            .stage       = AppEvent::" << sys.stage << ",\n";
            if (sys.run_in_editor) {
                ss << "            .flags       = ScriptFlag::RUN_IN_EDITOR,\n";
            } else {
                ss << "            .flags       = ScriptFlag::NONE,\n";
            }
            ss << "            .state_size  = 0,\n";
            ss << "            .state_align = 0,\n";
            ss << "            .queries     = " << sys.name << "__queries,\n";
            ss << "            .query_count = " << (sys.params.size() > 1 ? "1" : "0") << ",\n";
            ss << "        }";
            if (i + 1 < module.systems.size()) ss << ",";
            ss << "\n";
        }
        ss << "    };\n\n";
    }

    // 3. Component Inspectors
    ss << "    // =========================================================================\n";
    ss << "    // Component Inspectors\n";
    ss << "    // =========================================================================\n\n";

    for (const auto& comp : module.components) {
        std::string title = to_display_title(comp.name);
        std::string icon  = comp.icon;
        if (icon.empty()) {
            if (comp.category == "Camera") {
                icon = "LYRA_ICON_CAMERA";
            } else {
                icon = "LYRA_ICON_NODE";
            }
        }

        ss << "    inline void draw_inspector__" << comp.name << "(World& world, SceneNode node)\n    {\n";
        ss << "        if (!world.any_of<" << comp.name << ">(node)) return;\n";
        ss << "        auto& component = world.get_component<" << comp.name << ">(node);\n";
        ss << "        ui::section(\"" << title << "\", " << icon << ", [&]() {\n";
        ss << "            ui::properties([&]() {\n";

        for (const auto& field : comp.fields) {
            if (field.hidden) continue;

            std::string indent = "                ";
            if (!field.condition.empty()) {
                ss << indent << "if (component." << field.condition << ") {\n";
                indent = "                    ";
            }

            std::string label = field.label.empty() ? to_display_label(field.name) : field.label;

            if (ends_with(field.type, "bool") || field.drawer == "toggle") {
                ss << indent << "ui::toggle(\"" << label << "\", component." << field.name << ");\n";
            } else if (ends_with(field.type, "float") || ends_with(field.type, "double")) {
                std::string speed   = field.speed.empty() ? "0.1f" : field.speed;
                std::string min_v   = field.min_val.empty() ? "0.0f" : field.min_val;
                std::string max_v   = field.max_val.empty() ? "0.0f" : field.max_val;
                std::string reset_v = field.reset_val.empty() ? "0.0f" : field.reset_val;

                ss << indent << "ui::ScalarConfig " << field.name << "_cfg;\n";
                ss << indent << field.name << "_cfg.speed = " << speed << ";\n";
                ss << indent << field.name << "_cfg.min   = " << min_v << ";\n";
                ss << indent << field.name << "_cfg.max   = " << max_v << ";\n";
                if (!field.reset_val.empty()) {
                    ss << indent << field.name << "_cfg.reset = " << reset_v << ";\n";
                }
                ss << indent << "ui::number(\"" << label << "\", component." << field.name << ", " << field.name << "_cfg);\n";
            } else if (ends_with(field.type, "int") || ends_with(field.type, "uint") ||
                       ends_with(field.type, "uint32_t") || ends_with(field.type, "int32_t")) {
                std::string speed = field.speed.empty() ? "1" : field.speed;
                std::string min_v = field.min_val.empty() ? "0" : field.min_val;
                std::string max_v = field.max_val.empty() ? "0" : field.max_val;
                ss << indent << "ui::integer(\"" << label << "\", (int&)component." << field.name << ", "
                   << speed << ", " << min_v << ", " << max_v << ");\n";
            } else if (field.drawer == "color" || field.drawer == "color_picker" ||
                       to_lower_snake(field.name) == "color" || ends_with(field.type, "Color") || to_lower_snake(label) == "color") {
                if (field.drawer == "color_picker") {
                    ss << indent << "ui::color_picker(\"" << label << "\", component." << field.name << ");\n";
                } else {
                    ss << indent << "ui::color(\"" << label << "\", component." << field.name << ");\n";
                }
            } else if (ends_with(field.type, "Vector3")) {
                std::string speed = field.speed.empty() ? "0.1f" : field.speed;
                std::string min_v = field.min_val.empty() ? "0.0f" : field.min_val;
                std::string max_v = field.max_val.empty() ? "0.0f" : field.max_val;
                ss << indent << "ui::VectorConfig " << field.name << "_cfg;\n";
                ss << indent << field.name << "_cfg.speed = " << speed << ";\n";
                ss << indent << field.name << "_cfg.min   = " << min_v << ";\n";
                ss << indent << field.name << "_cfg.max   = " << max_v << ";\n";
                if (!field.reset_val.empty()) {
                    ss << indent << field.name << "_cfg.reset = " << field.reset_val << ";\n";
                }
                ss << indent << "ui::vec3(\"" << label << "\", component." << field.name << ", " << field.name << "_cfg);\n";
            } else if (ends_with(field.type, "Vector2")) {
                std::string speed = field.speed.empty() ? "0.1f" : field.speed;
                std::string min_v = field.min_val.empty() ? "0.0f" : field.min_val;
                std::string max_v = field.max_val.empty() ? "0.0f" : field.max_val;
                ss << indent << "ui::VectorConfig " << field.name << "_cfg;\n";
                ss << indent << field.name << "_cfg.speed = " << speed << ";\n";
                ss << indent << field.name << "_cfg.min   = " << min_v << ";\n";
                ss << indent << field.name << "_cfg.max   = " << max_v << ";\n";
                if (!field.reset_val.empty()) {
                    ss << indent << field.name << "_cfg.reset = " << field.reset_val << ";\n";
                }
                ss << indent << "ui::vec2(\"" << label << "\", component." << field.name << ", " << field.name << "_cfg);\n";
            } else if (ends_with(field.type, "Quaternion") || field.drawer == "euler") {
                ss << indent << "Vector3 " << field.name << "_euler = glm::degrees(glm::eulerAngles(component." << field.name << "));\n";
                ss << indent << "ui::vec3(\"" << label << "\", " << field.name << "_euler, [&]() {\n";
                ss << indent << "    component." << field.name << " = Quaternion(glm::radians(" << field.name << "_euler));\n";
                ss << indent << "});\n";
            } else {
                ss << indent << "if constexpr (std::is_enum_v<std::decay_t<decltype(component." << field.name << ")>>) {\n";
                ss << indent << "    ui::enumeration(\"" << label << "\", component." << field.name << ");\n";
                ss << indent << "} else if constexpr (requires { component." << field.name << ".valid(); }) {\n";
                ss << indent << "    ui::label(component." << field.name << ".valid() ? \"" << label << ": Bound\" : \"" << label << ": None\");\n";
                ss << indent << "}\n";
            }

            if (!field.condition.empty()) {
                ss << "                }\n";
            }
        }

        ss << "            });\n";
        ss << "        });\n";
        ss << "    }\n\n";
    }

    // 4. Component descriptors table
    ss << "    // =========================================================================\n";
    ss << "    // Component Descriptors Table\n";
    ss << "    // =========================================================================\n\n";

    if (module.components.empty()) {
        ss << "    inline constexpr const ComponentDescriptor* component_descriptors = nullptr;\n\n";
    } else {
        ss << "    inline constexpr ComponentDescriptor component_descriptors[] = {\n";
        for (size_t i = 0; i < module.components.size(); ++i) {
            const auto& comp = module.components[i];
            std::string icon = comp.icon;
            if (icon.empty()) {
                if (comp.category == "Camera") {
                    icon = "LYRA_ICON_CAMERA";
                } else {
                    icon = "LYRA_ICON_NODE";
                }
            }
            ss << "        {\n";
            ss << "            .name           = \"" << comp.name << "\",\n";
            ss << "            .category       = \"" << comp.category << "\",\n";
            ss << "            .icon           = " << icon << ",\n";
            ss << "            .has_component  = [](World& world, SceneNode node) -> bool { return world.any_of<" << comp.name << ">(node); },\n";
            ss << "            .draw_inspector = [](World& world, SceneNode node) { draw_inspector__" << comp.name << "(world, node); },\n";
            ss << "        }";
            if (i + 1 < module.components.size()) ss << ",";
            ss << "\n";
        }
        ss << "    };\n\n";
    }

    // 5. ScriptAPI factory
    ss << "    // =========================================================================\n";
    ss << "    // ScriptAPI Factory\n";
    ss << "    // =========================================================================\n\n";

    ss << "    inline auto create_script_api() -> ScriptAPI\n    {\n";
    ss << "        return ScriptAPI{\n";
    ss << "            .get_api_name = []() -> CString { return \"" << module.module_name << "\"; },\n";
    ss << "            .get_scripts = [](ScriptDescriptor* out) -> uint {\n";
    if (module.systems.empty()) {
        ss << "                return 0;\n";
    } else {
        ss << "                constexpr uint count = static_cast<uint>(std::size(script_descriptors));\n";
        ss << "                if (!out) {\n";
        ss << "                    return count;\n";
        ss << "                }\n";
        ss << "                for (uint i = 0; i < count; ++i) {\n";
        ss << "                    out[i] = script_descriptors[i];\n";
        ss << "                }\n";
        ss << "                return count;\n";
    }
    ss << "            },\n";
    ss << "            .run = [](ScriptID id, ScriptContext& ctx) {\n";

    for (const auto& sys : module.systems) {
        ss << "                if (id == hash_script_name(\"" << sys.name << "\")) {\n";
        ss << "                    " << sys.name << "__run(ctx);\n";
        ss << "                    return;\n";
        ss << "                }\n";
    }

    ss << "            },\n";
    ss << "            .get_params = nullptr,\n";
    ss << "            .get_components = [](ComponentDescriptor* out) -> uint {\n";
    if (module.components.empty()) {
        ss << "                return 0;\n";
    } else {
        ss << "                constexpr uint count = static_cast<uint>(std::size(component_descriptors));\n";
        ss << "                if (!out) {\n";
        ss << "                    return count;\n";
        ss << "                }\n";
        ss << "                for (uint i = 0; i < count; ++i) {\n";
        ss << "                    out[i] = component_descriptors[i];\n";
        ss << "                }\n";
        ss << "                return count;\n";
    }
    ss << "            },\n";
    ss << "        };\n";
    ss << "    }\n\n";

    std::string mod_ns = to_lower_snake(module.module_name);
    ss << "} // namespace lyra::generated::" << mod_ns << "\n\n";

    ss << "namespace lyra::scripts::" << mod_ns << "\n{\n";
    ss << "    auto create() -> ScriptAPI\n";
    ss << "    {\n";
    ss << "        return lyra::generated::" << mod_ns << "::create_script_api();\n";
    ss << "    }\n";
    ss << "} // namespace lyra::scripts::" << mod_ns << "\n\n";

    if (!is_cpp) {
        ss << "#endif // " << guard << "\n";
    }

    return ss.str();
}
