#pragma once

#ifndef LYRA_LYRA_FORMAT_MODELASSET_H
#define LYRA_LYRA_FORMAT_MODELASSET_H

#include <Lyra/Common/Math.h>
#include <Lyra/Common/String.h>
#include <Lyra/Common/Collections.h>
#include <Lyra/Assets/AMSAPI.h>
#include <Lyra/Assets/AMSUtils.h>
#include <Lyra/Format/MeshAsset.h>
#include <Lyra/Format/MaterialAsset.h>

namespace lyra
{

    /**
     * @brief A model asset acting as a prefab container for mesh/material hierarchy.
     *
     * Generated by asset cookers (GLTF, OBJ, STL) from raw DCC model files into Caches/models/.
     * Serialized as a USDA file (.model).
     */
    struct ModelAsset
    {
        static constexpr CString    name = "ModelAsset";
        static constexpr AssetTypeID type = 0xd32a1ea4;

        static auto loader() -> AssetLoaderAPI;
        static auto saver()  -> AssetSaverAPI;

        // stl cooker
        struct stl
        {
            static auto cooker() -> AssetCookerAPI;
        };

        // obj cooker
        struct obj
        {
            static auto cooker() -> AssetCookerAPI;
        };

        // gltf cooker (handles both .gltf and .glb)
        struct gltf
        {
            static auto cooker() -> AssetCookerAPI;
        };

        /**
         * @brief A node in the model hierarchy.
         */
        struct Node
        {
            String              name;
            Matrix4x4           transform = Matrix4x4(1.0f);
            MeshAssetHandle     mesh;     ///< Optional — invalid handle if no mesh.
            MaterialAssetHandle material; ///< Optional — invalid handle if no material.
            Vector<uint>        children; ///< Indices into the nodes array.
        };

        uint         root = 0;   ///< Index of the root node.
        Vector<Node> nodes;
    };

    using ModelAssetHandle = AssetHandle<ModelAsset>;

} // namespace lyra

#endif // LYRA_LYRA_FORMAT_MODELASSET_H
